CREATE TABLE IF NOT EXISTS Style(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  nickname VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS Album(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  date_create DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Track(
  id SERIAL PRIMARY KEY,
  duration INTEGER NOT NULL,
  album_id INTEGER NOT NULL REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Collection(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  date_create DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Style_artist(
  id SERIAL PRIMARY KEY,
  style_id INTEGER NOT NULL REFERENCES Style(id),
  artist_id INTEGER NOT NULL REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS  Album_artist(
  id SERIAL PRIMARY KEY,
  album_id INTEGER NOT NULL REFERENCES Album(id),
  artist_id INTEGER NOT NULL REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS Track_collection(
  id SERIAL PRIMARY KEY,
  track_id INTEGER NOT NULL REFERENCES Track(id),
  collection_id INTEGER NOT NULL REFERENCES Collection(id)
);
