CREATE TABLE IF NOT EXISTS style(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS artist(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  nickname VARCHAR(40) UNIQUE
);

CREATE TABLE IF NOT EXISTS album(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  date_create DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS track(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  duration INTEGER NOT NULL,
  album_id INTEGER NOT NULL REFERENCES album(id)
);

CREATE TABLE IF NOT EXISTS collection(
  id SERIAL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  date_create DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS style_artist(
  id SERIAL PRIMARY KEY,
  style_id INTEGER NOT NULL REFERENCES style(id),
  artist_id INTEGER NOT NULL REFERENCES artist(id)
);

CREATE TABLE IF NOT EXISTS  album_artist(
  id SERIAL PRIMARY KEY,
  album_id INTEGER NOT NULL REFERENCES album(id),
  artist_id INTEGER NOT NULL REFERENCES artist(id)
);

CREATE TABLE IF NOT EXISTS track_collection(
  id SERIAL PRIMARY KEY,
  track_id INTEGER NOT NULL REFERENCES track(id),
  collection_id INTEGER NOT NULL REFERENCES collection(id)
);
